spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkmate
    username: root
    password: Skeleton09@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect : org.hibernate.dialect.MySQL8Dialect
    show_sql: true

logging:
  level:
    org.hibernate.sql: info